todo/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'todo'
urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.RegisterPage.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='todo:login'), name='logout'),

    path('', views.TaskList.as_view(), name='index'),

    path('task/<int:pk>/', views.TaskDetail.as_view(), name='detail'),

    path('edit/<int:pk>/', views.TaskUpdate.as_view(), name='edit'),
    path('create/', views.TaskCreate.as_view(), name='create'),
    path('delete/<int:pk>/', views.TaskDelete.as_view(), name='delete'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    task_name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.task_name

    class Meta:
        ordering = ['complete']

todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse, reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


from .models import Task


class CustomLoginView(LoginView):
    template_name = 'todo/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('todo:index')


class RegisterPage(FormView):
    template_name = 'todo/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('todo:index')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('todo:index')
        return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'todo/index.html'

    def get_context_data(self, **kwargs):
        task_list = Task.objects.filter(user=self.request.user)
        incomplete_tasks = task_list.filter(complete=False)

        search_input = self.request.GET.get('search_area') or ''
        if search_input:
            task_list = task_list.filter(task_name__startswith=search_input)

        context = {"task_list": task_list,
                   "incomplete_tasks": incomplete_tasks,
                   "search_input": search_input, }
        return context

class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'todo/detail.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['task_name', 'description', 'complete']
    success_url = reverse_lazy('todo:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['task_name', 'description', 'complete']
    success_url = reverse_lazy('todo:index')


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('todo:index')

todo/templates/todo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>

</head>
<body>
    <div><a href="{%url 'todo:index' %}">Back</a></div>
    <h1>Task: {{object}}</h1>

</body>
</html>

todo/templates/todo/index.html
{% extends 'todo/main.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <h1>Hello {{request.user|title}}</h1>
        <h3 style="margin: 0">You have <i>{{incomplete_tasks|length}}</i> incomplete task{{incomplete_tasks|pluralize}}</h3>
    </div>



    {% if request.user.is_authenticated %}
        <a href="{% url 'todo:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'todo:login' %}">Login</a>
    {% endif %}
</div>

<div id="search-add-wrapper">
    <form action="" method="get" style="margin-top: 20px; display: flex;">
        <input type="text" name="search_area" value="{{search_input}}">
        <input class="button" type="submit" value="Search">
    </form>
    <a id="add-link" href="{% url 'todo:create' %}">&#x2b;</a>

</div>

<div class="task-items-wrapper">
    {% if task_list %}
        {% for task_name in task_list %}
            <div class="task-wrapper">
                {% if task_name.complete %}
                    <div class="task-title">
                        <div class="task-complete-icon"></div>
                        <i><s>{{task_name|truncatechars:25}}</s></i>
                        <div style="display: inline; margin-left:15px; color: lightgray;">
                            {{task_name.description|truncatechars:12}}
                        </div>
                    </div>
                {% else %}
                    <div class="task-title">
                        <div class="task-incomplete-icon"></div>
                        {{task_name|truncatechars:25}}
                        <div style="display: inline; margin-left:15px; color: lightgray;">
                            {{task_name.description|truncatechars:12}}
                        </div>
                    </div>

                {% endif %}
                <div>
                    <a class="edit-link" href="{% url 'todo:edit' task_name.id %}">&#9998;</a>
                    <a class="delete-link" href="{% url 'todo:delete' task_name.id %}">&#215;</a>
                </div>
            </div>
            {% endfor %}


    {% else %}
        <p>Nothing to do</p>
    {% endif %}
</div>

{% endblock content %}

todo/templates/todo/login.html
{% extends 'todo/main.html' %}
{% block content%}

<div class="header-bar">
    <h1>Login</h1>
</div>

<div class="card-body">
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Login">
    </form>

    <p>Don't have an account? <a href="{% url 'todo:register' %}">Register</a></p>
</div>
{% endblock content%}

todo/templates/todo/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To Do</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&family=Raleway:wght@200&display=swap" rel="stylesheet">
    <style>
        body {
            background-color: lightgray;
            font-family: 'Nunito', sans-serif;
            padding-top: 50px;
        }

        h1, h2, h3, h4, h5, h6 {
            font-family: 'Raleway', sans-serif;
        }

        .container {
            max-width: 550px;
            margin: auto;
            background-color: white;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21);
            box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21)
        }

        .header-bar {
            display: flex;
            justify-content: space-between;
            color: #fff;
            padding: 10px;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(90deg, #a8c2e8 0%, #6FA1EBFF 43%, #6FA1EBFF 100%);
        }

        .header-bar a {
            color: rgb(247, 247, 247);
            text-decoration: none;
        }

        .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px;
            background-color: #fff;
            border-top: 1px solid rgb(226, 226, 226)
        }

        .task-title {
            display: flex;
        }

        .task-complete-icon {
            margin-right: 10px;
            height: 20px;
            width: 20px;
            background-color: rgb(105, 192, 105);
            border-radius: 50%;
        }

        .task-incomplete-icon {
            margin-right: 10px;
            height: 20px;
            width: 20px;
            background-color: rgb(218, 218, 218);
            border-radius: 50%;
        }

        .delete-link, .edit-link {
            text-decoration: none;
            font-weight: 900;
            color: #cf4949;
            font-size: 22px;
            line-height: 0;
        }

        .edit-link {
            color: #496fcf;
            font-size: 17px;
            padding-right: 5px;
        }

        #search-add-wrapper {
            display: flex;
            justify-content:  space-between;
            align-items: center;
            padding: 10px;
        }

        #add-link {
            color: #6FA1EBFF;
            text-decoration: none;
            font-size: 42px;
            text-shadow: 1px 1px #2371ea;
        }

        input[type=text], input[type=password], textarea {
            border: 1px solid #6FA1EBFF;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
        }

        label {
            padding-top: 10px !important; ;
            display: block;
        }

        .button {
            border: 1px solid #6FA1EBFF;
            background-color: #FAFAFA;
            color: #6FA1EBFF;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }

        .card-body {
            padding: 20px;
        }

    </style>
</head>
<body>
      <div class="container">
        {% block content%}

        {% endblock content%}
      </div>
</body>
</html>

todo/templates/todo/register.html
{% extends 'todo/main.html' %}
{% block content%}

<div class="header-bar">
    <h1>Register</h1>
</div>
<div class="card-body">


    <form action="" method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style="margin-top: 10px;" class="button" type="submit" value="Register">
    </form>

    <p>Already have an account? <a href="{% url 'todo:login' %}">Login</a></p>
</div>
{% endblock content%}

todo/templates/todo/task_confirm_delete.html
{% extends 'todo/main.html' %}
{% block content%}
<div class="header-bar">
    <a href="{% url 'todo:index' %}">&#8592 Back</a>
</div>

<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        <p>Are you sure you want to delete this task? "{{task}}"</p>
        <input class="button" type="submit" value="Delete">
    </form>
</div>
{% endblock content%}

todo/templates/todo/task_form.html
{% extends 'todo/main.html' %}
{% block content%}

<div class="header-bar">
    <a href="{% url 'todo:index' %}">&#8592; Back</a>
</div>

<div class="card-body">
     <form method="POST" action="">
        {%csrf_token%}
        {{form.as_p}}
        <input class="button" type="submit" value="submit">
    </form>
</div>

{% endblock content%}